using Tyuiu.StachinskiiVS.Sprint3.Task0.V12.Lib;

DataService ds = new DataService();
Console.Title = "Спринт #3 | Выполнил: Стачинский В. C. | ИСПБ 24-1";
Console.WriteLine("********************************************************************************");
Console.WriteLine("* Спринт #3                                                                    *");
Console.WriteLine("* Тема: Базовые навыки работы в C#                                             *");
Console.WriteLine("* Задание #0                                                                   *");
Console.WriteLine("* Вариант #12                                                                  *");
Console.WriteLine("* Выполнил: Стачинский В. C. | ИСПБ 24-1                                       *");
Console.WriteLine("********************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                     *");
Console.WriteLine("* Написать программу используя цикл for, которая вычисляет произведение ряда   *");
Console.WriteLine("* по формуле, при t = 1                                                        *");
Console.WriteLine("********************************************************************************");
Console.WriteLine("********************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                             *");
Console.WriteLine("********************************************************************************");
int value = 1;
int startValue = 1;
int stopValue = 13;
Console.WriteLine("Переменная t = " + value);
Console.WriteLine("Старт шага = " + startValue);
Console.WriteLine("Конец шага = " + stopValue);
Console.WriteLine("********************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                                   *");
Console.WriteLine("********************************************************************************");
Console.WriteLine("Произведение ряда = " + ds.GetMultiplySeries(value, startValue, stopValue));
Console.ReadKey();