using Tyuiu.StachinskiiVS.Sprint3.Task3.V4.Lib;

DataService ds = new DataService();
string str = "plkjjdw cvjkl";
char letter = 'j';
Console.Title = "Спринт #2 | Выполнил: Стачинский В.С. | ИСПб-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #3                                                               *");
Console.WriteLine("* Тема: Оператор цикла foreach                                            *");
Console.WriteLine("* Задание #3                                                              *");
Console.WriteLine("* Вариант #4                                                              *");
Console.WriteLine("* Выполнил: Стачинский В.С. | ИСПб-24-1                                   *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Используя цикл foreach удалить из строки все буквы j в строке           *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
Console.WriteLine($" Искомая строка: {str}");
Console.WriteLine($" Искомая буква, которую нужно удалить: {letter}");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
Console.WriteLine($" Строка в итоге: {ds.DeleteCharInString(str, letter)}");
Console.ReadKey();